defaults:
  - datadims : [label_dims,embedding_dims, downstream_downsample]
  - supervised_encoder : [resnet-supervised, basset-supervised]
  - hydra : multirun 
  - override hydra/launcher: joblib # ability to launch jobs in parallel fashion
  - _self_
hydra :
  searchpath:
    - file://conf 
  sweeper:
    params:
      embedder : gena-lm-bigbird-base-t2t,
                 gena-lm-bert-large-t2,
                 hyenadna-tiny-1k,
                 hyenadna-small-32k,
                 hyenadna-medium-160k,
                 hyenadna-medium-450k,
                 hyenadna-large-1m,
                 dnabert6,
                 resnetlm,
                 nt_transformer_ms,
                 nt_transformer_human_ref,
                 nt_transformer_1000g,
                 dnabert2,
                 onehot,
                 awdlstm,
                 resnet-supervised,
                 nt_transformer_v2_500m,
                 grover
task : gene_finding 
embedder : onehot
output_dir: ./downstream_tasks/${task}/${embedder}/
model:
  _target_: bend.models.downstream.CNN
  input_size: ${datadims.${embedder}}
  output_size: ${datadims.${task}}
  hidden_size: 64
  kernel_size: 3
optimizer : 
  _target_ : torch.optim.AdamW 
  lr : 0.003
  weight_decay: 0.01
data:
  _target_: bend.utils.data_downstream.get_data
  cross_validation : false
  batch_size : 64
  num_workers : 0
  padding_value : -100
  shuffle : 1000
  parent_dir : ./data
  data_dir : ${data.parent_dir}/${task}/${embedder}/
params:
  epochs: 100
  load_checkpoint: false
  mode: train
  gradient_accumulation_steps: 1
  criterion: cross_entropy
  class_weights: null #[6.37, 1485.62, 1.52, 1485.62, 6.11, 1438.04, 1.52, 1438.04, 1.0]
  metric : mcc
  activation : none
wandb:
  mode : disabled 